-- Enable pgvector extension for vector similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Business context table for RAG
CREATE TABLE IF NOT EXISTS business_context (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  context_type TEXT NOT NULL CHECK (context_type IN ('goal', 'kpi', 'brand', 'budget', 'campaign', 'industry')),
  content TEXT NOT NULL,
  metadata JSONB DEFAULT '{}'::jsonb,
  embedding vector(1536),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_business_context_user_id ON business_context(user_id);
CREATE INDEX IF NOT EXISTS idx_business_context_type ON business_context(user_id, context_type);
CREATE INDEX IF NOT EXISTS idx_business_context_created ON business_context(created_at DESC);

-- Vector similarity index using IVFFlat
CREATE INDEX IF NOT EXISTS idx_business_context_embedding 
  ON business_context 
  USING ivfflat (embedding vector_cosine_ops)
  WITH (lists = 100);

-- Row Level Security
ALTER TABLE business_context ENABLE ROW LEVEL SECURITY;

-- Users can only access their own context
CREATE POLICY "Users can view own context"
  ON business_context
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own context"
  ON business_context
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own context"
  ON business_context
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own context"
  ON business_context
  FOR DELETE
  USING (auth.uid() = user_id);

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION update_business_context_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to auto-update updated_at
CREATE TRIGGER business_context_updated_at
  BEFORE UPDATE ON business_context
  FOR EACH ROW
  EXECUTE FUNCTION update_business_context_updated_at();

-- Add comment for documentation
COMMENT ON TABLE business_context IS 'Stores business context (goals, KPIs, brand info) with vector embeddings for RAG-enhanced AI insights';
COMMENT ON COLUMN business_context.embedding IS 'Vector embedding (1536 dimensions) generated by OpenAI text-embedding-3-small';
COMMENT ON COLUMN business_context.context_type IS 'Type of business context: goal, kpi, brand, budget, campaign, or industry';
